steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/evident-lock-337908/testing', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/evident-lock-337908/testing']
availableSecrets:
  secretManager:
  - versionName: projects/evident-lock-337908/secrets/github_key/versions/1
    env: 'GITHUB_KEY'
  - versionName: projects/evident-lock-337908/secrets/wandb_api_key/versions/1
    env: 'WANDB_KEY'